export const MAJOR=['C','D♭','D','E♭','E','F','G♭','G','A♭','A','B♭','B'];
export const MINOR=['C','C♯','D','E♭','E','F','F♯','G','G♯','A','B♭','B'];
const letters='CDEFGAB', naturals=[0,2,4,5,7,9,11];
export const mod=n=>((n%12)+12)%12;
export function pc(n){return mod(naturals[letters.indexOf(n[0])]+[...n.slice(1)].reduce((a,c)=>a+(c==='♯'||c==='#'?1:c==='♭'||c==='b'?-1:0),0));}
export function spell(root,degree,offset){const l=(letters.indexOf(root[0])+degree)%7;let delta=mod(pc(root)+offset-naturals[l]);if(delta>6)delta-=12;return letters[l]+(delta>0?'♯'.repeat(delta):'♭'.repeat(-delta));}
export function scale(key,minor=false){return (minor?[0,2,3,5,7,8,10]:[0,2,4,5,7,9,11]).map((n,i)=>spell(key,i,n));}
export const romanMajor=['I','ii','iii','IV','V','vi','vii°'],romanMinor=['i','ii°','III','iv','v','VI','VII'];
export function chord(key,minor,item){const s=scale(key,minor), source=item.borrowed?scale(key,!minor):s;let root=source[item.degree];const base=[0,2,4].map(n=>source[(item.degree+n)%7]);let ints=base.map(n=>mod(pc(n)-pc(root)));let quality=ints[1]===3?(ints[2]===6?'dim':'minor'):'major';let ext=item.ext||'triad';let degrees=[0,2,4],semitones=[0,quality==='major'?4:3,quality==='dim'?6:7];let suffix=quality==='minor'?'m':quality==='dim'?'dim':'';
if(ext==='sus2'||ext==='sus4'){degrees=[0,ext==='sus2'?1:3,4];semitones=[0,ext==='sus2'?2:5,7];suffix=ext;}
else if(ext!=='triad'){
if(ext==='7'||ext==='9'){degrees.push(6);semitones.push(10);suffix=quality==='minor'?'m'+ext:quality==='dim'?(ext==='7'?'m7♭5':'m9♭5'):ext;}
if(ext==='maj7'||ext==='maj9'){degrees.push(6);semitones.push(11);suffix=(quality==='minor'?'m(maj'+(ext==='maj9'?'9':'7')+')':quality==='dim'?'dim('+ext+')':ext);}
if(ext==='9'||ext==='maj9'||ext==='add9'){degrees.push(8);semitones.push(14);if(ext==='add9')suffix+='add9';}
}
const notes=degrees.map((d,i)=>spell(root,d,semitones[i]));const romans=item.borrowed?(minor?romanMajor:romanMinor):(minor?romanMinor:romanMajor);const chromatic=notes.filter(n=>!s.some(a=>pc(a)===pc(n)));
let func=item.degree===0||item.degree===2||item.degree===5?'Tonic':item.degree===1||item.degree===3?'Predominant':'Dominant';if(minor&&!item.borrowed&&(item.degree===4||item.degree===6))func='Modal tension';
return {root,name:root+suffix,quality,ext,notes,degrees,semitones,roman:(item.borrowed&&!minor&&[2,5,6].includes(item.degree)?'♭':'')+romans[item.degree],func,chromatic,borrowed:!!item.borrowed,degree:item.degree};}
export function diatonicExtension(key,minor,item){let c=chord(key,minor,{...item,ext:'triad'}),s=item.borrowed?scale(key,!minor):scale(key,minor);let seventh=mod(pc(s[(item.degree+6)%7])-pc(c.root));return seventh===11?'maj7':'7';}
export function describe(c,key){if(c.borrowed)return 'Borrowed colour from the parallel key.';if(c.func==='Tonic')return c.degree===0?'Home. Stable and resolved.':'A softer resting place.';if(c.func==='Predominant')return 'Moves away from home, towards V.';if(c.func==='Modal tension')return 'Gentle pull; no raised leading tone.';return 'Tension that draws you home.';}
function at(n,min){return min+mod(pc(n)-mod(min));}
function noteAt(n,midi){return {name:n,midi,octave:Math.floor((midi-(n[0]==='B'&&n.includes('♯')?1:n[0]==='C'&&n.includes('♭')?-1:0))/12)-1};}
export function voicings(chords,{voicing='Open',hands='Root + fifth',smooth=true,register='Middle'}={}){let prev=null;return chords.map(c=>{let root=at(c.root,register==='Low'?33:register==='High'?45:38);if(root>49&&register!=='High')root-=12;let lh=[noteAt(c.root,root)];if(hands==='Root + fifth')lh.push(noteAt(c.notes[2],root+c.semitones[2]));if(hands==='Octave bass')lh.push(noteAt(c.root,root+12));
let indices=c.notes.map((_,i)=>i);let omitted=[];if(c.notes.length>4){indices=indices.filter(i=>i!==2);omitted=['5th omitted from RH'+(hands==='Root + fifth'?' · present in LH':'')];}
if(hands!=='Simple'&&indices.length>3)indices=indices.filter(i=>i!==0);
let target=register==='Low'?53:register==='High'?65:59;let candidates=[];for(let inv=0;inv<indices.length;inv++){let order=[...indices.slice(inv),...indices.slice(0,inv)];for(let base=target-4;base<=target+7;base++){let cursor=base;let notes=order.map((idx,j)=>{let m=at(c.notes[idx],cursor);cursor=m+1;return noteAt(c.notes[idx],m)});if(voicing==='Open'&&notes.length===4){/* spread between hands; RH remains within a ninth */notes=notes.filter(n=>mod(n.midi)!==pc(c.root));}if(voicing==='Wide'&&notes.length>2&&notes[notes.length-1].midi-notes[0].midi<9)notes[notes.length-1].midi+=12;
let span=notes.at(-1).midi-notes[0].midi;if(span>14||notes[0].midi<=lh.at(-1).midi+2)continue;notes=notes.map(n=>noteAt(n.name,n.midi));let movement=prev?notes.reduce((a,n,i)=>a+Math.abs(n.midi-prev[Math.min(i,prev.length-1)].midi),0):0;let score=(smooth?movement:inv*12)+Math.abs(notes[0].midi-target)*.7+Math.max(0,span-12)*4; if(voicing==='Closed')score+=span*.5; candidates.push({notes,score});}}
candidates.sort((a,b)=>a.score-b.score);let rh=candidates[0]?.notes||indices.map(i=>noteAt(c.notes[i],at(c.notes[i],60))).sort((a,b)=>a.midi-b.midi);let common=prev?rh.filter(n=>prev.some(p=>p.midi===n.midi)).map(n=>n.name):[];prev=rh;let played=[...lh,...rh].map(n=>pc(n.name));let missing=c.notes.filter(n=>!played.includes(pc(n)));if(missing.length&&!omitted.length)omitted.push('Omitted: '+missing.join(' · '));return {lh,rh,omitted,common,bass:c.root,inversion:'Root in bass'};});}
export const noteText=n=>n.name+n.octave;
export function movement(v,type,key,minor){let a=v.rh.map(noteText),b=v.lh.map(noteText);const s=scale(key,minor);let top=v.rh.at(-1),idx=s.findIndex(n=>pc(n)===pc(top.name));let neighbour=idx<0?s.find(n=>mod(pc(n)-pc(top.name))<=2):s[(idx+1)%7];let next=noteText(noteAt(neighbour,at(neighbour,top.midi+1)));switch(type){case'Rolling':return {lh:b.join(' → '),rh:[...a,a[0]].join(' → '),tip:'Bass first, then roll upwards through the harmony.'};case'Broken chord':return {lh:b.join(' + '),rh:[a[0],a.at(-1),...a.slice(1,-1),a.at(-1)].join(' → '),tip:'Alternate lower and upper tones with an even pulse.'};case'Repeated inner note':return {lh:b.join(' + '),rh:[a[0],a[1],a.at(-1),a[1]].join(' → '),tip:'Let the inner note anchor the changing harmony.'};case'Neighbour movement':return {lh:b.join(' + '),rh:[a.at(-1),next,a.at(-1)].join(' → '),tip:'Hold the lower harmony; move above and back to the top tone.'};default:return {lh:b.join(' + '),rh:a.join(' + '),tip:'Play each hand together; let the chord settle.'};}}
